=== TimFontaine/Rose/src/main/resources/client.xsd
<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:clt="http://NamespaceTest.tim/client"
targetNamespace="http://NamespaceTest.tim/client"
elementFormDefault="qualified" >

<xsd:import schemaLocation="test.xsd" 
           namespace="http://NamespaceTest.tim/Types"/>
           
    <xsd:element name="root" type="clt:clientConfig" />
		<xsd:complexType name="clientConfig">
			<xsd:sequence>
				<xsd:element name="unitDefaultAbility" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="gameActionProps" type="clt:gameActionProp" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		
		</xsd:complexType>   	
		

	<xsd:complexType name="gameActionProp">
		<xsd:all>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="gameType" type="xsd:string"/>
			<xsd:element name="actionObject" type="xsd:string" />
			<xsd:element name="accelerator" type="xsd:string" minOccurs="0"/>
			<xsd:element name="image" type="xsd:string" minOccurs="0"/>
		</xsd:all>
	</xsd:complexType>
</xsd:schema>

=== TimFontaine/Rose/client.xml
<root xmlns="http://NamespaceTest.tim/client" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://NamespaceTest.tim/client src/main/resources/client.xsd">

<unitDefaultAbility>destroy</unitDefaultAbility>
<unitDefaultAbility>skip</unitDefaultAbility>

	
<gameActionProps>
	<name>buildCityAction</name>
	<gameType>build</gameType>
	<actionObject>buildCityAction</actionObject>
	<actionClass>BuildCityAction</actionClass>
	<accelerator>B</accelerator>
	<image>dot</image>
</gameActionProps>
<gameActionProps>
	<name>buildRoadAction</name>
	<gameType>build</gameType>
	<actionObject>buildRoadAction</actionObject>
	<actionClass>DummyAction</actionClass>
	<image>road</image>
</gameActionProps>

<gameActionProps>
	<name>destroy</name>
	<gameType>other</gameType>
	<actionObject>destroyAction</actionObject>
	<actionClass>DummyAction</actionClass>
	<image>mountain</image>
</gameActionProps>		

<gameActionProps>
	<name>skip</name>
	<gameType>other</gameType>
	<actionObject>skipAction</actionObject>
	<actionClass>DummyAction</actionClass>
	<image>mountain</image>
</gameActionProps>		

<gameActionProps>
	<name>move</name>
	<gameType>basicAction</gameType>
	<actionObject>move</actionObject>
	<actionClass>MoveAction</actionClass>
	<accelerator>left.LEFT</accelerator>
	<accelerator>right.RIGHT</accelerator>
	<accelerator>up.UP</accelerator>
	<accelerator>down.DOWN</accelerator>
	<image></image>
</gameActionProps>

<gameActionProps>
	<name>mapControls</name>
	<gameType>mapControlsAction</gameType>
	<actionObject>mapControls</actionObject>
	<actionClass>MapControlsAction</actionClass>
	<image></image>
</gameActionProps>



</root>
